theme: minima
url: "https://yarinnaftali.github.io"

# Navigation menu
nav:
  - name: "דף הבית"
    link: "/"
  # - name: "אודות"
  #   link: "/about.html"

markdown: kramdown
kramdown:
  parse_block_html: true
